HelloWorld.V3.Web/Models/HelloWorldViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace HelloWorld.V3.Models
{
    public class HelloWorldViewModel
    {
        public int Id { get; set; }

        [Required]
        public string Message { get; set; }

        [Required]
        public string Name { get; set; }
    }
}

HelloWorld.V3.Web/Controllers/HelloWorldController.cs
using AutoMapper;
using HelloWorld.V3.Domain;
using HelloWorld.V3.Models;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace HelloWorld.V3.Controllers
{
    public class HelloWorldController : Controller
    {
        private readonly IHelloWorldService _service;

        public HelloWorldController(IHelloWorldService service)
        {
            this._service = service;
        }
        public async Task<ActionResult> Index()
        {
            var models = await _service.GetAllAsync();

            var viewModels = Mapper.Map<List<HelloWorldViewModel>>(models);

            return View(viewModels);
        }

        public ActionResult Create()
        {
            return View(new HelloWorldViewModel());
        }

        [HttpPost]
        public async Task<ActionResult> Create(HelloWorldViewModel model)
        {
            await _service.CreateAsync(Mapper.Map<HelloWorldModel>(model));

            return RedirectToAction(nameof(HelloWorldController.Index));
        }
    }
}

HelloWorld.V3.Web/Views/HelloWorld/Create.cshtml
@{
    ViewBag.Title = "Create";
}

@model HelloWorld.V3.Models.HelloWorldViewModel


<div class="row">
    <div class="col-md-4">
        @using (Html.BeginForm())
        {
            <div class="form-group">

                @Html.LabelFor(l => l.Message):
                <p>
                    @Html.ValidationMessageFor(l => l.Message)
                </p>
                @Html.TextBoxFor(l => l.Message, new { @class = "form-control" })
            </div>

            <div class="form-group">

                @Html.LabelFor(l => l.Name):
                <p>
                    @Html.ValidationMessageFor(l => l.Name)
                </p>
                @Html.TextBoxFor(l => l.Name, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <button class="btn btn-primary">Save</button>
            </div>
        }
    </div>
</div>

HelloWorld.V3.Web/Views/HelloWorld/Index.cshtml
@{
    ViewBag.Title = "Index";
}

@model  List<HelloWorld.V3.Models.HelloWorldViewModel>


<div class="row">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Message</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Message</td>
                </tr>
            }
        </tbody>
    </table>

</div>

HelloWorld.V3.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello World Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Hello World", "Index", "HelloWorld", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("List View", "Index", "HelloWorld")</li>
                    <li>@Html.ActionLink("Create new Hello World", "Create", "HelloWorld")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Hell World App</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>